server:
  port: 8081

spring:
  application:
    name: kafka-consumer
  kafka:
    template:
      observation-enabled: true
    listener:
      ack-mode: batch
      concurrency: 1
      type: batch
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      properties:
        specific.avro.reader: true
