server:
  port: 8081

spring:
  application:
    name: kafka-consumer
  kafka:
    template:
      observation-enabled: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true