server:
  port: 8080

spring:
  application:
    name: kafka-producer
  kafka:
    template:
      observation-enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      compression-type: lz4
      properties:
        linger.ms: 20
        auto.register.schemas: false
        avro.remove.java.properties: true
  threads:
    virtual:
      enabled: true