server:
  port: 8080

spring:
  application:
    name: kafka
  kafka:
    bootstrap-servers: localhost:29092
    template:
      observation-enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      compression-type: lz4
      properties:
        linger.ms: 20
        auto.register.schemas: false
        avro.remove.java.properties: true
    properties:
      security:
        protocol: PLAINTEXT
      schema:
        registry:
          url: http://localhost:28081
  threads:
    virtual:
      enabled: true

abonne:
  abonne-topic: abonne-event