spring:
  kafka:
    bootstrap-servers: localhost:29092
    properties:
      security:
        protocol: PLAINTEXT
      schema:
        registry:
          url: http://localhost:28081

abonne:
  abonne-topic: abonne-event